version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    target-branch: main
    groups:
      npm-minor-patch:
        update-types:
          - minor
          - patch
