// PATCH /api/admin/payouts/[id] — mark a payout as paid (or unmark).
// DELETE /api/admin/payouts/[id] — remove a payout that was generated by mistake.

import { NextResponse } from "next/server";
import { getSupabaseAdmin } from "@/lib/supabase-admin";
import { requireAdmin } from "@/lib/platform-admin";

export const runtime = "nodejs";

interface PatchBody {
  paid: boolean;
  paid_reference?: string;
  notes?: string;
}

export async function PATCH(req: Request, { params }: { params: Promise<{ id: string }> }) {
  const auth = await requireAdmin(req);
  if (!auth.ok) {
    return NextResponse.json({ error: auth.error }, { status: auth.status });
  }
  const { id } = await params;

  let body: PatchBody;
  try {
    body = (await req.json()) as PatchBody;
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const admin = getSupabaseAdmin();
  const patch: Record<string, unknown> = {};
  if (body.paid) {
    patch.paid_at = new Date().toISOString();
    patch.paid_by_user_id = auth.userId;
    patch.paid_reference = body.paid_reference?.trim() || null;
  } else {
    patch.paid_at = null;
    patch.paid_by_user_id = null;
    patch.paid_reference = null;
  }
  if (typeof body.notes === "string") patch.notes = body.notes.trim() || null;

  const { data, error } = await admin
    .from("commission_payouts")
    .update(patch)
    .eq("id", id)
    .select("id, period_start, period_end, total_referrals_active, total_mrr_zar, commission_pct, commission_amount_zar, paid_at, paid_reference, notes, created_at")
    .single();

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  return NextResponse.json({ payout: data });
}

export async function DELETE(req: Request, { params }: { params: Promise<{ id: string }> }) {
  const auth = await requireAdmin(req);
  if (!auth.ok) {
    return NextResponse.json({ error: auth.error }, { status: auth.status });
  }
  const { id } = await params;
  const admin = getSupabaseAdmin();
  const { error } = await admin.from("commission_payouts").delete().eq("id", id);
  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
  return NextResponse.json({ ok: true });
}
