#!/usr/bin/env python3
"""build_rollback.py — emit rollback_119.sql from pg_policy_pre119.csv.

For every table migration 119 touches, DROP every policy 119 could have
created (including the FOR-ALL decompose products) and re-CREATE every
pre-119 policy row on that table verbatim from the dump, then DROP the
helper function. One transaction, same lock/statement timeouts as 119.

Dry-run check (see the migration plan Task 12):
  bash docs/superpowers/plans/artifacts/rig_load.sh          # synth + 119
  docker exec -i rls_rig psql -U postgres -d postgres -v ON_ERROR_STOP=1 \
      -f - < docs/superpowers/plans/artifacts/rollback_119.sql
  # then dump pg_policy and diff the touched-table rows against the CSV -> identical
"""
import csv
import os

HERE = os.path.dirname(os.path.abspath(__file__))
PRE_CSV = os.path.join(HERE, "pg_policy_pre119.csv")
OUT = os.path.join(HERE, "rollback_119.sql")

CMD = {"r": "SELECT", "a": "INSERT", "w": "UPDATE", "d": "DELETE", "*": "ALL"}

# Tables migration 119 touches (every other table is left exactly as-is).
TOUCHED = [
    # Part 2 canonical
    "app_settings", "categories", "expense_categories", "ingredients", "locations",
    "payment_methods", "production_log", "products", "purchases", "ra_notes",
    "recipes", "stock_receipt_items", "stock_receipts", "suppliers",
    # Part 3 explicit
    "balance_adjustments", "stock_adjustments", "sales", "combos", "promotions",
    "purchase_orders", "location_settings", "report_subscriptions",
    "product_location_prices",
    # Part 4 FOR ALL decompose
    "wms_adjustments", "wms_catalog", "wms_dispatch_items", "wms_dispatches",
    "wms_inventory", "wms_po_items", "wms_purchase_orders", "wms_receipt_items",
    "wms_receipts", "wms_stock_count_audit", "wms_stock_counts",
    "wms_stock_count_sessions", "wms_locations", "wms_org_settings",
    "zra_config", "zra_invoices",
    # Part 5 child
    "combo_items", "promotion_items", "purchase_order_items",
    # Part 6 Bucket B
    "customer_payments", "customers", "shifts", "daily_reconciliation",
    "stock_count_audit",
]
FORALL = [
    "wms_adjustments", "wms_catalog", "wms_dispatch_items", "wms_dispatches",
    "wms_inventory", "wms_po_items", "wms_purchase_orders", "wms_receipt_items",
    "wms_receipts", "wms_stock_count_audit", "wms_stock_counts",
    "wms_stock_count_sessions", "wms_locations", "wms_org_settings",
    "zra_config", "zra_invoices",
]


def main():
    pre = {}
    with open(PRE_CSV, newline="", encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            pre.setdefault(row["tbl"], []).append(row)

    out = []
    w = out.append
    w("-- ============================================================")
    w("-- Rollback for migration 119 (role-scoped write RLS).")
    w("-- GENERATED by build_rollback.py from pg_policy_pre119.csv — do not hand-edit.")
    w("-- Restores every touched table's policy set to its exact pre-119 state")
    w("-- and drops public.current_user_manager_org_ids().")
    w("-- Apply: Supabase SQL Editor. Then: npx supabase migration repair --status reverted 119")
    w("-- ============================================================")
    w("")
    w("BEGIN;")
    w("SET LOCAL lock_timeout = '5s';")
    w("SET LOCAL statement_timeout = '120s';")
    w("")

    for t in TOUCHED:
        rows = pre.get(t, [])
        w(f"-- ---- {t} ----------------------------------------------------")
        # drop everything 119 may have created / left on this table
        names = sorted({r["polname"] for r in rows})
        if t in FORALL:
            names = sorted(set(names) | {
                f"{t}_org_read", f"{t}_org_insert", f"{t}_org_update", f"{t}_org_delete",
            })
        for n in names:
            w(f'DROP POLICY IF EXISTS "{n}" ON public.{t};')
        # recreate the pre-119 rows verbatim
        for r in rows:
            using = (r["using_expr"] or "").strip()
            check = (r["check_expr"] or "").strip()
            stmt = f'CREATE POLICY "{r["polname"]}" ON public.{t} FOR {CMD[r["polcmd"]]}'
            if using:
                stmt += f"\n  USING ({using})"
            if check:
                stmt += f"\n  WITH CHECK ({check})"
            stmt += ";"
            w(stmt)
        w("")

    w("DROP FUNCTION IF EXISTS public.current_user_manager_org_ids();")
    w("")
    w("COMMIT;")

    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(out))
    print(f"wrote {OUT} ({len(TOUCHED)} touched tables)")


if __name__ == "__main__":
    main()
