#!/usr/bin/env python3
"""Build synth_schema.sql — a synthetic policy-layer DB for verifying migration 119.

Reads pg_policy_pre119.csv + columns_pre119.csv (owner-provided prod dump) and
emits a bare-Postgres schema that reproduces ONLY the RLS surface migration 119
touches: one stub table per policy-bearing table, stub SETOF-uuid helper
functions, a real org_members table, and every CREATE POLICY row verbatim.

No Supabase stack. Load into the `rls_rig` container:
  docker exec -i rls_rig psql -U postgres -d postgres -v ON_ERROR_STOP=1 -f - < synth_schema.sql
"""
import csv
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
POLICY_CSV = os.path.join(HERE, "pg_policy_pre119.csv")
COLUMNS_CSV = os.path.join(HERE, "columns_pre119.csv")
OUT = os.path.join(HERE, "synth_schema.sql")

CMD_MAP = {"r": "SELECT", "a": "INSERT", "w": "UPDATE", "d": "DELETE", "*": "ALL"}

# Identifiers that must never be emitted as a stub column: SQL keywords,
# base columns already on every stub table, helper/function names, subquery
# table names and their aliases seen in the dump.
STOPLIST = {
    # keywords / operators
    "select", "from", "where", "and", "or", "in", "exists", "is", "not",
    "as", "on", "any", "all", "array", "text", "true", "false", "null",
    "join", "case", "when", "then", "else", "end", "distinct",
    # base columns present on every stub table
    "id", "org_id", "location_id", "recorded_by_user_id",
    # helper functions (stubbed) + auth
    "current_user_org_ids", "current_user_writable_org_ids",
    "current_user_location_ids", "current_user_manager_org_ids",
    "is_platform_admin", "auth", "uid", "gen_random_uuid",
    # subquery table names referenced by policy exprs
    "combos", "promotions", "purchase_orders", "partners", "platform_admins",
    "org_members", "org_members_1", "expenses",
    # common subquery aliases in the dump
    "m", "om", "pa", "r",
    # column of the real org_members table (created explicitly); user_id is
    # intentionally NOT stoplisted — partners/platform_admins subqueries need it.
    "role",
}

IDENT_RE = re.compile(r"[a-z_][a-z0-9_]*")


def read_policies():
    with open(POLICY_CSV, newline="", encoding="utf-8") as fh:
        rdr = csv.DictReader(fh)
        return list(rdr)


def read_columns():
    cols = {}
    with open(COLUMNS_CSV, newline="", encoding="utf-8") as fh:
        rdr = csv.DictReader(fh)
        for row in rdr:
            cols.setdefault(row["table_name"], set()).add(row["column_name"])
    return cols


def main():
    rows = read_policies()
    col_dump = read_columns()

    tables = []
    seen = set()
    for row in rows:
        t = row["tbl"]
        if t not in seen:
            seen.add(t)
            tables.append(t)

    all_table_names = set(tables)

    # extra stub columns referenced by a table's own policy expressions
    extra_cols = {t: set() for t in tables}
    for row in rows:
        t = row["tbl"]
        blob = " ".join(filter(None, [row["using_expr"], row["check_expr"]]))
        blob = re.sub(r"'[^']*'", " ", blob)  # drop string literals ('owner', 'admin_pin', ...)
        blob = blob.lower()
        for ident in IDENT_RE.findall(blob):
            if ident in STOPLIST:
                continue
            if ident in all_table_names:
                continue
            if ident in col_dump.get(t, set()):
                continue
            extra_cols[t].add(ident)

    out = []
    w = out.append
    w("-- GENERATED by build_synth.py — do not edit by hand.")
    w("-- Synthetic policy-layer schema for verifying migration 119 on bare postgres:16.")
    w("")
    w("CREATE EXTENSION IF NOT EXISTS pgcrypto;")
    w("")
    w("-- Supabase runtime roles the migration REVOKE/GRANTs against")
    w("DO $$ BEGIN")
    w("  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN CREATE ROLE anon; END IF;")
    w("  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN CREATE ROLE authenticated; END IF;")
    w("END $$;")
    w("")
    w("-- auth schema + stub auth.uid()")
    w("CREATE SCHEMA IF NOT EXISTS auth;")
    w("CREATE OR REPLACE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT NULL::uuid $$;")
    w("")
    w("-- stub SETOF-uuid helpers (return nothing — structural verification only)")
    for fn in ("current_user_org_ids", "current_user_writable_org_ids", "current_user_location_ids"):
        w(f"CREATE OR REPLACE FUNCTION public.{fn}() RETURNS SETOF uuid LANGUAGE sql STABLE AS $$ SELECT NULL::uuid WHERE false $$;")
    w("CREATE OR REPLACE FUNCTION public.is_platform_admin() RETURNS boolean LANGUAGE sql STABLE AS $$ SELECT false $$;")
    w("")
    w("-- real org_members (helper bodies read it) + platform_admins stub")
    w("CREATE TABLE IF NOT EXISTS public.org_members (")
    w("  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),")
    w("  org_id uuid, user_id uuid, role text);")
    w("CREATE TABLE IF NOT EXISTS public.platform_admins (")
    w("  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),")
    w("  user_id uuid);")
    w("")

    w("-- ---- stub tables ------------------------------------------------------")
    for t in tables:
        if t in ("org_members", "platform_admins"):
            continue
        w(f"CREATE TABLE IF NOT EXISTS public.{t} (")
        w("  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),")
        w("  org_id uuid,")
        w("  location_id uuid,")
        w("  recorded_by_user_id uuid")
        w(");")
        for c in sorted(extra_cols[t]):
            ctype = "uuid" if c.endswith("_id") else "text"
            w(f"ALTER TABLE public.{t} ADD COLUMN IF NOT EXISTS {c} {ctype};")
    w("")

    w("-- ---- policies (verbatim from the prod dump) -------------------------")
    for row in rows:
        t = row["tbl"]
        pol = row["polname"]
        cmd = CMD_MAP[row["polcmd"]]
        using = (row["using_expr"] or "").strip()
        check = (row["check_expr"] or "").strip()
        stmt = f'CREATE POLICY "{pol}" ON public.{t} FOR {cmd}'
        if using:
            stmt += f"\n  USING ({using})"
        if check:
            stmt += f"\n  WITH CHECK ({check})"
        stmt += ";"
        w(stmt)
    w("")

    w("-- ---- enable RLS ---------------------------------------------------")
    for t in tables:
        w(f"ALTER TABLE public.{t} ENABLE ROW LEVEL SECURITY;")
    w("")

    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(out))
    print(f"wrote {OUT} ({len(tables)} tables, {len(rows)} policies)")
    added = {t: sorted(c) for t, c in extra_cols.items() if c}
    if added:
        print("extra stub columns added:")
        for t, c in sorted(added.items()):
            print(f"  {t}: {', '.join(c)}")


if __name__ == "__main__":
    main()
