-- ============================================================
-- Rollback for migration 119 (role-scoped write RLS).
-- GENERATED by build_rollback.py from pg_policy_pre119.csv — do not hand-edit.
-- Restores every touched table's policy set to its exact pre-119 state
-- and drops public.current_user_manager_org_ids().
-- Apply: Supabase SQL Editor. Then: npx supabase migration repair --status reverted 119
-- ============================================================

BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '120s';

-- ---- app_settings ----------------------------------------------------
DROP POLICY IF EXISTS "app_settings_org_delete" ON public.app_settings;
DROP POLICY IF EXISTS "app_settings_org_insert" ON public.app_settings;
DROP POLICY IF EXISTS "app_settings_org_read" ON public.app_settings;
DROP POLICY IF EXISTS "app_settings_org_update" ON public.app_settings;
CREATE POLICY "app_settings_org_insert" ON public.app_settings FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "app_settings_org_delete" ON public.app_settings FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "app_settings_org_read" ON public.app_settings FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "app_settings_org_update" ON public.app_settings FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));

-- ---- categories ----------------------------------------------------
DROP POLICY IF EXISTS "categories_org_delete" ON public.categories;
DROP POLICY IF EXISTS "categories_org_insert" ON public.categories;
DROP POLICY IF EXISTS "categories_org_read" ON public.categories;
DROP POLICY IF EXISTS "categories_org_update" ON public.categories;
CREATE POLICY "categories_org_insert" ON public.categories FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "categories_org_delete" ON public.categories FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "categories_org_read" ON public.categories FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "categories_org_update" ON public.categories FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));

-- ---- expense_categories ----------------------------------------------------
DROP POLICY IF EXISTS "expense_categories_org_delete" ON public.expense_categories;
DROP POLICY IF EXISTS "expense_categories_org_insert" ON public.expense_categories;
DROP POLICY IF EXISTS "expense_categories_org_read" ON public.expense_categories;
DROP POLICY IF EXISTS "expense_categories_org_update" ON public.expense_categories;
CREATE POLICY "expense_categories_org_insert" ON public.expense_categories FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "expense_categories_org_delete" ON public.expense_categories FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "expense_categories_org_read" ON public.expense_categories FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "expense_categories_org_update" ON public.expense_categories FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));

-- ---- ingredients ----------------------------------------------------
DROP POLICY IF EXISTS "ingredients_org_delete" ON public.ingredients;
DROP POLICY IF EXISTS "ingredients_org_insert" ON public.ingredients;
DROP POLICY IF EXISTS "ingredients_org_read" ON public.ingredients;
DROP POLICY IF EXISTS "ingredients_org_update" ON public.ingredients;
CREATE POLICY "ingredients_org_insert" ON public.ingredients FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "ingredients_org_delete" ON public.ingredients FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "ingredients_org_read" ON public.ingredients FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "ingredients_org_update" ON public.ingredients FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));

-- ---- locations ----------------------------------------------------
DROP POLICY IF EXISTS "locations_org_delete" ON public.locations;
DROP POLICY IF EXISTS "locations_org_insert" ON public.locations;
DROP POLICY IF EXISTS "locations_org_read" ON public.locations;
DROP POLICY IF EXISTS "locations_org_update" ON public.locations;
CREATE POLICY "locations_org_insert" ON public.locations FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "locations_org_delete" ON public.locations FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "locations_org_read" ON public.locations FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "locations_org_update" ON public.locations FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));

-- ---- payment_methods ----------------------------------------------------
DROP POLICY IF EXISTS "payment_methods_org_delete" ON public.payment_methods;
DROP POLICY IF EXISTS "payment_methods_org_insert" ON public.payment_methods;
DROP POLICY IF EXISTS "payment_methods_org_read" ON public.payment_methods;
DROP POLICY IF EXISTS "payment_methods_org_update" ON public.payment_methods;
CREATE POLICY "payment_methods_org_insert" ON public.payment_methods FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "payment_methods_org_delete" ON public.payment_methods FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "payment_methods_org_read" ON public.payment_methods FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "payment_methods_org_update" ON public.payment_methods FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));

-- ---- production_log ----------------------------------------------------
DROP POLICY IF EXISTS "production_log_org_delete" ON public.production_log;
DROP POLICY IF EXISTS "production_log_org_insert" ON public.production_log;
DROP POLICY IF EXISTS "production_log_org_read" ON public.production_log;
DROP POLICY IF EXISTS "production_log_org_update" ON public.production_log;
CREATE POLICY "production_log_org_insert" ON public.production_log FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "production_log_org_delete" ON public.production_log FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "production_log_org_read" ON public.production_log FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "production_log_org_update" ON public.production_log FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));

-- ---- products ----------------------------------------------------
DROP POLICY IF EXISTS "products_org_delete" ON public.products;
DROP POLICY IF EXISTS "products_org_insert" ON public.products;
DROP POLICY IF EXISTS "products_org_read" ON public.products;
DROP POLICY IF EXISTS "products_org_update" ON public.products;
CREATE POLICY "products_org_insert" ON public.products FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "products_org_delete" ON public.products FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "products_org_read" ON public.products FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "products_org_update" ON public.products FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));

-- ---- purchases ----------------------------------------------------
DROP POLICY IF EXISTS "purchases_org_delete" ON public.purchases;
DROP POLICY IF EXISTS "purchases_org_insert" ON public.purchases;
DROP POLICY IF EXISTS "purchases_org_read" ON public.purchases;
DROP POLICY IF EXISTS "purchases_org_update" ON public.purchases;
CREATE POLICY "purchases_org_insert" ON public.purchases FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "purchases_org_delete" ON public.purchases FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "purchases_org_read" ON public.purchases FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "purchases_org_update" ON public.purchases FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));

-- ---- ra_notes ----------------------------------------------------
DROP POLICY IF EXISTS "ra_notes_org_delete" ON public.ra_notes;
DROP POLICY IF EXISTS "ra_notes_org_insert" ON public.ra_notes;
DROP POLICY IF EXISTS "ra_notes_org_read" ON public.ra_notes;
DROP POLICY IF EXISTS "ra_notes_org_update" ON public.ra_notes;
CREATE POLICY "ra_notes_org_insert" ON public.ra_notes FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "ra_notes_org_delete" ON public.ra_notes FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "ra_notes_org_read" ON public.ra_notes FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "ra_notes_org_update" ON public.ra_notes FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));

-- ---- recipes ----------------------------------------------------
DROP POLICY IF EXISTS "recipes_org_delete" ON public.recipes;
DROP POLICY IF EXISTS "recipes_org_insert" ON public.recipes;
DROP POLICY IF EXISTS "recipes_org_read" ON public.recipes;
DROP POLICY IF EXISTS "recipes_org_update" ON public.recipes;
CREATE POLICY "recipes_org_insert" ON public.recipes FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "recipes_org_delete" ON public.recipes FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "recipes_org_read" ON public.recipes FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "recipes_org_update" ON public.recipes FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));

-- ---- stock_receipt_items ----------------------------------------------------
DROP POLICY IF EXISTS "stock_receipt_items_org_delete" ON public.stock_receipt_items;
DROP POLICY IF EXISTS "stock_receipt_items_org_insert" ON public.stock_receipt_items;
DROP POLICY IF EXISTS "stock_receipt_items_org_read" ON public.stock_receipt_items;
DROP POLICY IF EXISTS "stock_receipt_items_org_update" ON public.stock_receipt_items;
CREATE POLICY "stock_receipt_items_org_insert" ON public.stock_receipt_items FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "stock_receipt_items_org_delete" ON public.stock_receipt_items FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "stock_receipt_items_org_read" ON public.stock_receipt_items FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "stock_receipt_items_org_update" ON public.stock_receipt_items FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));

-- ---- stock_receipts ----------------------------------------------------
DROP POLICY IF EXISTS "stock_receipts_org_delete" ON public.stock_receipts;
DROP POLICY IF EXISTS "stock_receipts_org_insert" ON public.stock_receipts;
DROP POLICY IF EXISTS "stock_receipts_org_read" ON public.stock_receipts;
DROP POLICY IF EXISTS "stock_receipts_org_update" ON public.stock_receipts;
CREATE POLICY "stock_receipts_org_insert" ON public.stock_receipts FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "stock_receipts_org_delete" ON public.stock_receipts FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "stock_receipts_org_read" ON public.stock_receipts FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "stock_receipts_org_update" ON public.stock_receipts FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));

-- ---- suppliers ----------------------------------------------------
DROP POLICY IF EXISTS "suppliers_org_delete" ON public.suppliers;
DROP POLICY IF EXISTS "suppliers_org_insert" ON public.suppliers;
DROP POLICY IF EXISTS "suppliers_org_read" ON public.suppliers;
DROP POLICY IF EXISTS "suppliers_org_update" ON public.suppliers;
CREATE POLICY "suppliers_org_insert" ON public.suppliers FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "suppliers_org_delete" ON public.suppliers FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "suppliers_org_read" ON public.suppliers FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "suppliers_org_update" ON public.suppliers FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));

-- ---- balance_adjustments ----------------------------------------------------
DROP POLICY IF EXISTS "balance_adjustments_loc_delete" ON public.balance_adjustments;
DROP POLICY IF EXISTS "balance_adjustments_loc_insert" ON public.balance_adjustments;
DROP POLICY IF EXISTS "balance_adjustments_loc_read" ON public.balance_adjustments;
DROP POLICY IF EXISTS "balance_adjustments_loc_update" ON public.balance_adjustments;
CREATE POLICY "balance_adjustments_loc_insert" ON public.balance_adjustments FOR INSERT
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "balance_adjustments_loc_delete" ON public.balance_adjustments FOR DELETE
  USING (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "balance_adjustments_loc_read" ON public.balance_adjustments FOR SELECT
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "balance_adjustments_loc_update" ON public.balance_adjustments FOR UPDATE
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))))
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));

-- ---- stock_adjustments ----------------------------------------------------
DROP POLICY IF EXISTS "stock_adjustments_loc_delete" ON public.stock_adjustments;
DROP POLICY IF EXISTS "stock_adjustments_loc_insert" ON public.stock_adjustments;
DROP POLICY IF EXISTS "stock_adjustments_loc_read" ON public.stock_adjustments;
DROP POLICY IF EXISTS "stock_adjustments_loc_update" ON public.stock_adjustments;
CREATE POLICY "stock_adjustments_loc_insert" ON public.stock_adjustments FOR INSERT
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "stock_adjustments_loc_delete" ON public.stock_adjustments FOR DELETE
  USING (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "stock_adjustments_loc_read" ON public.stock_adjustments FOR SELECT
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "stock_adjustments_loc_update" ON public.stock_adjustments FOR UPDATE
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))))
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));

-- ---- sales ----------------------------------------------------
DROP POLICY IF EXISTS "sales_loc_delete" ON public.sales;
DROP POLICY IF EXISTS "sales_loc_insert" ON public.sales;
DROP POLICY IF EXISTS "sales_loc_read" ON public.sales;
DROP POLICY IF EXISTS "sales_loc_update" ON public.sales;
CREATE POLICY "sales_loc_insert" ON public.sales FOR INSERT
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "sales_loc_delete" ON public.sales FOR DELETE
  USING (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "sales_loc_read" ON public.sales FOR SELECT
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "sales_loc_update" ON public.sales FOR UPDATE
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))))
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));

-- ---- combos ----------------------------------------------------
DROP POLICY IF EXISTS "combos_delete" ON public.combos;
DROP POLICY IF EXISTS "combos_insert" ON public.combos;
DROP POLICY IF EXISTS "combos_read" ON public.combos;
DROP POLICY IF EXISTS "combos_update" ON public.combos;
CREATE POLICY "combos_insert" ON public.combos FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "combos_delete" ON public.combos FOR DELETE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "combos_read" ON public.combos FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "combos_update" ON public.combos FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));

-- ---- promotions ----------------------------------------------------
DROP POLICY IF EXISTS "promotions_delete" ON public.promotions;
DROP POLICY IF EXISTS "promotions_insert" ON public.promotions;
DROP POLICY IF EXISTS "promotions_read" ON public.promotions;
DROP POLICY IF EXISTS "promotions_update" ON public.promotions;
CREATE POLICY "promotions_insert" ON public.promotions FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "promotions_delete" ON public.promotions FOR DELETE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "promotions_read" ON public.promotions FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "promotions_update" ON public.promotions FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));

-- ---- purchase_orders ----------------------------------------------------
DROP POLICY IF EXISTS "purchase_orders_delete" ON public.purchase_orders;
DROP POLICY IF EXISTS "purchase_orders_insert" ON public.purchase_orders;
DROP POLICY IF EXISTS "purchase_orders_read" ON public.purchase_orders;
DROP POLICY IF EXISTS "purchase_orders_update" ON public.purchase_orders;
CREATE POLICY "purchase_orders_insert" ON public.purchase_orders FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "purchase_orders_delete" ON public.purchase_orders FOR DELETE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "purchase_orders_read" ON public.purchase_orders FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "purchase_orders_update" ON public.purchase_orders FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));

-- ---- location_settings ----------------------------------------------------
DROP POLICY IF EXISTS "location_settings_delete" ON public.location_settings;
DROP POLICY IF EXISTS "location_settings_insert" ON public.location_settings;
DROP POLICY IF EXISTS "location_settings_read" ON public.location_settings;
DROP POLICY IF EXISTS "location_settings_update" ON public.location_settings;
CREATE POLICY "location_settings_insert" ON public.location_settings FOR INSERT
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids))));
CREATE POLICY "location_settings_delete" ON public.location_settings FOR DELETE
  USING (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids))));
CREATE POLICY "location_settings_read" ON public.location_settings FOR SELECT
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)) AND ((key <> ALL (ARRAY['admin_pin'::text, 'cashier_pin'::text])) OR (EXISTS ( SELECT 1
   FROM org_members om
  WHERE ((om.org_id = location_settings.org_id) AND (om.user_id = auth.uid()) AND (om.role = ANY (ARRAY['owner'::text, 'admin'::text]))))))));
CREATE POLICY "location_settings_update" ON public.location_settings FOR UPDATE
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids))))
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids))));

-- ---- report_subscriptions ----------------------------------------------------
DROP POLICY IF EXISTS "report_subs_delete" ON public.report_subscriptions;
DROP POLICY IF EXISTS "report_subs_insert" ON public.report_subscriptions;
DROP POLICY IF EXISTS "report_subs_read" ON public.report_subscriptions;
DROP POLICY IF EXISTS "report_subs_update" ON public.report_subscriptions;
CREATE POLICY "report_subs_insert" ON public.report_subscriptions FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "report_subs_delete" ON public.report_subscriptions FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "report_subs_read" ON public.report_subscriptions FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "report_subs_update" ON public.report_subscriptions FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));

-- ---- product_location_prices ----------------------------------------------------
DROP POLICY IF EXISTS "plp_delete" ON public.product_location_prices;
DROP POLICY IF EXISTS "plp_insert" ON public.product_location_prices;
DROP POLICY IF EXISTS "plp_read" ON public.product_location_prices;
DROP POLICY IF EXISTS "plp_update" ON public.product_location_prices;
CREATE POLICY "plp_insert" ON public.product_location_prices FOR INSERT
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids))));
CREATE POLICY "plp_delete" ON public.product_location_prices FOR DELETE
  USING (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids))));
CREATE POLICY "plp_read" ON public.product_location_prices FOR SELECT
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids))));
CREATE POLICY "plp_update" ON public.product_location_prices FOR UPDATE
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids))))
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids))));

-- ---- wms_adjustments ----------------------------------------------------
DROP POLICY IF EXISTS "org_isolation" ON public.wms_adjustments;
DROP POLICY IF EXISTS "wms_adjustments_org_delete" ON public.wms_adjustments;
DROP POLICY IF EXISTS "wms_adjustments_org_insert" ON public.wms_adjustments;
DROP POLICY IF EXISTS "wms_adjustments_org_read" ON public.wms_adjustments;
DROP POLICY IF EXISTS "wms_adjustments_org_update" ON public.wms_adjustments;
CREATE POLICY "org_isolation" ON public.wms_adjustments FOR ALL
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));

-- ---- wms_catalog ----------------------------------------------------
DROP POLICY IF EXISTS "org_isolation" ON public.wms_catalog;
DROP POLICY IF EXISTS "wms_catalog_org_delete" ON public.wms_catalog;
DROP POLICY IF EXISTS "wms_catalog_org_insert" ON public.wms_catalog;
DROP POLICY IF EXISTS "wms_catalog_org_read" ON public.wms_catalog;
DROP POLICY IF EXISTS "wms_catalog_org_update" ON public.wms_catalog;
CREATE POLICY "org_isolation" ON public.wms_catalog FOR ALL
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));

-- ---- wms_dispatch_items ----------------------------------------------------
DROP POLICY IF EXISTS "org_isolation" ON public.wms_dispatch_items;
DROP POLICY IF EXISTS "wms_dispatch_items_org_delete" ON public.wms_dispatch_items;
DROP POLICY IF EXISTS "wms_dispatch_items_org_insert" ON public.wms_dispatch_items;
DROP POLICY IF EXISTS "wms_dispatch_items_org_read" ON public.wms_dispatch_items;
DROP POLICY IF EXISTS "wms_dispatch_items_org_update" ON public.wms_dispatch_items;
CREATE POLICY "org_isolation" ON public.wms_dispatch_items FOR ALL
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));

-- ---- wms_dispatches ----------------------------------------------------
DROP POLICY IF EXISTS "org_isolation" ON public.wms_dispatches;
DROP POLICY IF EXISTS "wms_dispatches_org_delete" ON public.wms_dispatches;
DROP POLICY IF EXISTS "wms_dispatches_org_insert" ON public.wms_dispatches;
DROP POLICY IF EXISTS "wms_dispatches_org_read" ON public.wms_dispatches;
DROP POLICY IF EXISTS "wms_dispatches_org_update" ON public.wms_dispatches;
CREATE POLICY "org_isolation" ON public.wms_dispatches FOR ALL
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));

-- ---- wms_inventory ----------------------------------------------------
DROP POLICY IF EXISTS "org_isolation" ON public.wms_inventory;
DROP POLICY IF EXISTS "wms_inventory_org_delete" ON public.wms_inventory;
DROP POLICY IF EXISTS "wms_inventory_org_insert" ON public.wms_inventory;
DROP POLICY IF EXISTS "wms_inventory_org_read" ON public.wms_inventory;
DROP POLICY IF EXISTS "wms_inventory_org_update" ON public.wms_inventory;
CREATE POLICY "org_isolation" ON public.wms_inventory FOR ALL
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));

-- ---- wms_po_items ----------------------------------------------------
DROP POLICY IF EXISTS "org_isolation" ON public.wms_po_items;
DROP POLICY IF EXISTS "wms_po_items_org_delete" ON public.wms_po_items;
DROP POLICY IF EXISTS "wms_po_items_org_insert" ON public.wms_po_items;
DROP POLICY IF EXISTS "wms_po_items_org_read" ON public.wms_po_items;
DROP POLICY IF EXISTS "wms_po_items_org_update" ON public.wms_po_items;
CREATE POLICY "org_isolation" ON public.wms_po_items FOR ALL
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));

-- ---- wms_purchase_orders ----------------------------------------------------
DROP POLICY IF EXISTS "org_isolation" ON public.wms_purchase_orders;
DROP POLICY IF EXISTS "wms_purchase_orders_org_delete" ON public.wms_purchase_orders;
DROP POLICY IF EXISTS "wms_purchase_orders_org_insert" ON public.wms_purchase_orders;
DROP POLICY IF EXISTS "wms_purchase_orders_org_read" ON public.wms_purchase_orders;
DROP POLICY IF EXISTS "wms_purchase_orders_org_update" ON public.wms_purchase_orders;
CREATE POLICY "org_isolation" ON public.wms_purchase_orders FOR ALL
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));

-- ---- wms_receipt_items ----------------------------------------------------
DROP POLICY IF EXISTS "org_isolation" ON public.wms_receipt_items;
DROP POLICY IF EXISTS "wms_receipt_items_org_delete" ON public.wms_receipt_items;
DROP POLICY IF EXISTS "wms_receipt_items_org_insert" ON public.wms_receipt_items;
DROP POLICY IF EXISTS "wms_receipt_items_org_read" ON public.wms_receipt_items;
DROP POLICY IF EXISTS "wms_receipt_items_org_update" ON public.wms_receipt_items;
CREATE POLICY "org_isolation" ON public.wms_receipt_items FOR ALL
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));

-- ---- wms_receipts ----------------------------------------------------
DROP POLICY IF EXISTS "org_isolation" ON public.wms_receipts;
DROP POLICY IF EXISTS "wms_receipts_org_delete" ON public.wms_receipts;
DROP POLICY IF EXISTS "wms_receipts_org_insert" ON public.wms_receipts;
DROP POLICY IF EXISTS "wms_receipts_org_read" ON public.wms_receipts;
DROP POLICY IF EXISTS "wms_receipts_org_update" ON public.wms_receipts;
CREATE POLICY "org_isolation" ON public.wms_receipts FOR ALL
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));

-- ---- wms_stock_count_audit ----------------------------------------------------
DROP POLICY IF EXISTS "org_isolation" ON public.wms_stock_count_audit;
DROP POLICY IF EXISTS "wms_stock_count_audit_org_delete" ON public.wms_stock_count_audit;
DROP POLICY IF EXISTS "wms_stock_count_audit_org_insert" ON public.wms_stock_count_audit;
DROP POLICY IF EXISTS "wms_stock_count_audit_org_read" ON public.wms_stock_count_audit;
DROP POLICY IF EXISTS "wms_stock_count_audit_org_update" ON public.wms_stock_count_audit;
CREATE POLICY "org_isolation" ON public.wms_stock_count_audit FOR ALL
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));

-- ---- wms_stock_counts ----------------------------------------------------
DROP POLICY IF EXISTS "org_isolation" ON public.wms_stock_counts;
DROP POLICY IF EXISTS "wms_stock_counts_org_delete" ON public.wms_stock_counts;
DROP POLICY IF EXISTS "wms_stock_counts_org_insert" ON public.wms_stock_counts;
DROP POLICY IF EXISTS "wms_stock_counts_org_read" ON public.wms_stock_counts;
DROP POLICY IF EXISTS "wms_stock_counts_org_update" ON public.wms_stock_counts;
CREATE POLICY "org_isolation" ON public.wms_stock_counts FOR ALL
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));

-- ---- wms_stock_count_sessions ----------------------------------------------------
DROP POLICY IF EXISTS "wms_scs_org_isolation" ON public.wms_stock_count_sessions;
DROP POLICY IF EXISTS "wms_stock_count_sessions_org_delete" ON public.wms_stock_count_sessions;
DROP POLICY IF EXISTS "wms_stock_count_sessions_org_insert" ON public.wms_stock_count_sessions;
DROP POLICY IF EXISTS "wms_stock_count_sessions_org_read" ON public.wms_stock_count_sessions;
DROP POLICY IF EXISTS "wms_stock_count_sessions_org_update" ON public.wms_stock_count_sessions;
CREATE POLICY "wms_scs_org_isolation" ON public.wms_stock_count_sessions FOR ALL
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));

-- ---- wms_locations ----------------------------------------------------
DROP POLICY IF EXISTS "wms_locations_org_delete" ON public.wms_locations;
DROP POLICY IF EXISTS "wms_locations_org_insert" ON public.wms_locations;
DROP POLICY IF EXISTS "wms_locations_org_read" ON public.wms_locations;
DROP POLICY IF EXISTS "wms_locations_org_update" ON public.wms_locations;
DROP POLICY IF EXISTS "wms_locations_org_write" ON public.wms_locations;
CREATE POLICY "wms_locations_org_write" ON public.wms_locations FOR ALL
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "wms_locations_org_read" ON public.wms_locations FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));

-- ---- wms_org_settings ----------------------------------------------------
DROP POLICY IF EXISTS "wms_org_settings_org_delete" ON public.wms_org_settings;
DROP POLICY IF EXISTS "wms_org_settings_org_insert" ON public.wms_org_settings;
DROP POLICY IF EXISTS "wms_org_settings_org_read" ON public.wms_org_settings;
DROP POLICY IF EXISTS "wms_org_settings_org_update" ON public.wms_org_settings;
DROP POLICY IF EXISTS "wms_org_settings_org_write" ON public.wms_org_settings;
CREATE POLICY "wms_org_settings_org_write" ON public.wms_org_settings FOR ALL
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "wms_org_settings_org_read" ON public.wms_org_settings FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));

-- ---- zra_config ----------------------------------------------------
DROP POLICY IF EXISTS "zra_config_org_delete" ON public.zra_config;
DROP POLICY IF EXISTS "zra_config_org_insert" ON public.zra_config;
DROP POLICY IF EXISTS "zra_config_org_read" ON public.zra_config;
DROP POLICY IF EXISTS "zra_config_org_update" ON public.zra_config;
DROP POLICY IF EXISTS "zra_config_read" ON public.zra_config;
DROP POLICY IF EXISTS "zra_config_write" ON public.zra_config;
CREATE POLICY "zra_config_write" ON public.zra_config FOR ALL
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "zra_config_read" ON public.zra_config FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));

-- ---- zra_invoices ----------------------------------------------------
DROP POLICY IF EXISTS "zra_invoices_org_delete" ON public.zra_invoices;
DROP POLICY IF EXISTS "zra_invoices_org_insert" ON public.zra_invoices;
DROP POLICY IF EXISTS "zra_invoices_org_read" ON public.zra_invoices;
DROP POLICY IF EXISTS "zra_invoices_org_update" ON public.zra_invoices;
DROP POLICY IF EXISTS "zra_invoices_read" ON public.zra_invoices;
DROP POLICY IF EXISTS "zra_invoices_write" ON public.zra_invoices;
CREATE POLICY "zra_invoices_write" ON public.zra_invoices FOR ALL
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "zra_invoices_read" ON public.zra_invoices FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));

-- ---- combo_items ----------------------------------------------------
DROP POLICY IF EXISTS "combo_items_delete" ON public.combo_items;
DROP POLICY IF EXISTS "combo_items_insert" ON public.combo_items;
DROP POLICY IF EXISTS "combo_items_read" ON public.combo_items;
CREATE POLICY "combo_items_insert" ON public.combo_items FOR INSERT
  WITH CHECK ((combo_id IN ( SELECT combos.id
   FROM combos
  WHERE (combos.org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))));
CREATE POLICY "combo_items_delete" ON public.combo_items FOR DELETE
  USING ((combo_id IN ( SELECT combos.id
   FROM combos
  WHERE (combos.org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))));
CREATE POLICY "combo_items_read" ON public.combo_items FOR SELECT
  USING ((combo_id IN ( SELECT combos.id
   FROM combos
  WHERE (combos.org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))));

-- ---- promotion_items ----------------------------------------------------
DROP POLICY IF EXISTS "promotion_items_delete" ON public.promotion_items;
DROP POLICY IF EXISTS "promotion_items_insert" ON public.promotion_items;
DROP POLICY IF EXISTS "promotion_items_read" ON public.promotion_items;
CREATE POLICY "promotion_items_insert" ON public.promotion_items FOR INSERT
  WITH CHECK ((promotion_id IN ( SELECT promotions.id
   FROM promotions
  WHERE (promotions.org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))));
CREATE POLICY "promotion_items_delete" ON public.promotion_items FOR DELETE
  USING ((promotion_id IN ( SELECT promotions.id
   FROM promotions
  WHERE (promotions.org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))));
CREATE POLICY "promotion_items_read" ON public.promotion_items FOR SELECT
  USING ((promotion_id IN ( SELECT promotions.id
   FROM promotions
  WHERE (promotions.org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))));

-- ---- purchase_order_items ----------------------------------------------------
DROP POLICY IF EXISTS "purchase_order_items_delete" ON public.purchase_order_items;
DROP POLICY IF EXISTS "purchase_order_items_insert" ON public.purchase_order_items;
DROP POLICY IF EXISTS "purchase_order_items_read" ON public.purchase_order_items;
CREATE POLICY "purchase_order_items_insert" ON public.purchase_order_items FOR INSERT
  WITH CHECK ((po_id IN ( SELECT purchase_orders.id
   FROM purchase_orders
  WHERE (purchase_orders.org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))));
CREATE POLICY "purchase_order_items_delete" ON public.purchase_order_items FOR DELETE
  USING ((po_id IN ( SELECT purchase_orders.id
   FROM purchase_orders
  WHERE (purchase_orders.org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))));
CREATE POLICY "purchase_order_items_read" ON public.purchase_order_items FOR SELECT
  USING ((po_id IN ( SELECT purchase_orders.id
   FROM purchase_orders
  WHERE (purchase_orders.org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))));

-- ---- customer_payments ----------------------------------------------------
DROP POLICY IF EXISTS "customer_payments_loc_delete" ON public.customer_payments;
DROP POLICY IF EXISTS "customer_payments_loc_insert" ON public.customer_payments;
DROP POLICY IF EXISTS "customer_payments_loc_read" ON public.customer_payments;
DROP POLICY IF EXISTS "customer_payments_loc_update" ON public.customer_payments;
CREATE POLICY "customer_payments_loc_insert" ON public.customer_payments FOR INSERT
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "customer_payments_loc_delete" ON public.customer_payments FOR DELETE
  USING (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "customer_payments_loc_read" ON public.customer_payments FOR SELECT
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "customer_payments_loc_update" ON public.customer_payments FOR UPDATE
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))))
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));

-- ---- customers ----------------------------------------------------
DROP POLICY IF EXISTS "customers_loc_delete" ON public.customers;
DROP POLICY IF EXISTS "customers_loc_insert" ON public.customers;
DROP POLICY IF EXISTS "customers_loc_read" ON public.customers;
DROP POLICY IF EXISTS "customers_loc_update" ON public.customers;
CREATE POLICY "customers_loc_insert" ON public.customers FOR INSERT
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "customers_loc_delete" ON public.customers FOR DELETE
  USING (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "customers_loc_read" ON public.customers FOR SELECT
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "customers_loc_update" ON public.customers FOR UPDATE
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))))
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));

-- ---- shifts ----------------------------------------------------
DROP POLICY IF EXISTS "shifts_loc_delete" ON public.shifts;
DROP POLICY IF EXISTS "shifts_loc_insert" ON public.shifts;
DROP POLICY IF EXISTS "shifts_loc_read" ON public.shifts;
DROP POLICY IF EXISTS "shifts_loc_update" ON public.shifts;
CREATE POLICY "shifts_loc_insert" ON public.shifts FOR INSERT
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "shifts_loc_delete" ON public.shifts FOR DELETE
  USING (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "shifts_loc_read" ON public.shifts FOR SELECT
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "shifts_loc_update" ON public.shifts FOR UPDATE
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))))
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));

-- ---- daily_reconciliation ----------------------------------------------------
DROP POLICY IF EXISTS "daily_reconciliation_org_delete" ON public.daily_reconciliation;
DROP POLICY IF EXISTS "daily_reconciliation_org_insert" ON public.daily_reconciliation;
DROP POLICY IF EXISTS "daily_reconciliation_org_read" ON public.daily_reconciliation;
DROP POLICY IF EXISTS "daily_reconciliation_org_update" ON public.daily_reconciliation;
CREATE POLICY "daily_reconciliation_org_insert" ON public.daily_reconciliation FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "daily_reconciliation_org_delete" ON public.daily_reconciliation FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "daily_reconciliation_org_read" ON public.daily_reconciliation FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "daily_reconciliation_org_update" ON public.daily_reconciliation FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));

-- ---- stock_count_audit ----------------------------------------------------
DROP POLICY IF EXISTS "stock_count_audit_org_delete" ON public.stock_count_audit;
DROP POLICY IF EXISTS "stock_count_audit_org_insert" ON public.stock_count_audit;
DROP POLICY IF EXISTS "stock_count_audit_org_read" ON public.stock_count_audit;
DROP POLICY IF EXISTS "stock_count_audit_org_update" ON public.stock_count_audit;
CREATE POLICY "stock_count_audit_org_insert" ON public.stock_count_audit FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "stock_count_audit_org_delete" ON public.stock_count_audit FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "stock_count_audit_org_read" ON public.stock_count_audit FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "stock_count_audit_org_update" ON public.stock_count_audit FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));

DROP FUNCTION IF EXISTS public.current_user_manager_org_ids();

COMMIT;