-- GENERATED by build_synth.py — do not edit by hand.
-- Synthetic policy-layer schema for verifying migration 119 on bare postgres:16.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Supabase runtime roles the migration REVOKE/GRANTs against
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN CREATE ROLE anon; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN CREATE ROLE authenticated; END IF;
END $$;

-- auth schema + stub auth.uid()
CREATE SCHEMA IF NOT EXISTS auth;
CREATE OR REPLACE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT NULL::uuid $$;

-- stub SETOF-uuid helpers (return nothing — structural verification only)
CREATE OR REPLACE FUNCTION public.current_user_org_ids() RETURNS SETOF uuid LANGUAGE sql STABLE AS $$ SELECT NULL::uuid WHERE false $$;
CREATE OR REPLACE FUNCTION public.current_user_writable_org_ids() RETURNS SETOF uuid LANGUAGE sql STABLE AS $$ SELECT NULL::uuid WHERE false $$;
CREATE OR REPLACE FUNCTION public.current_user_location_ids() RETURNS SETOF uuid LANGUAGE sql STABLE AS $$ SELECT NULL::uuid WHERE false $$;
CREATE OR REPLACE FUNCTION public.is_platform_admin() RETURNS boolean LANGUAGE sql STABLE AS $$ SELECT false $$;

-- real org_members (helper bodies read it) + platform_admins stub
CREATE TABLE IF NOT EXISTS public.org_members (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid, user_id uuid, role text);
CREATE TABLE IF NOT EXISTS public.platform_admins (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid);

-- ---- stub tables ------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.admin_org_overrides (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
ALTER TABLE public.admin_org_overrides ADD COLUMN IF NOT EXISTS user_id uuid;
CREATE TABLE IF NOT EXISTS public.app_settings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.balance_adjustments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.categories (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.combo_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
ALTER TABLE public.combo_items ADD COLUMN IF NOT EXISTS combo_id uuid;
CREATE TABLE IF NOT EXISTS public.combos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.commission_payouts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
ALTER TABLE public.commission_payouts ADD COLUMN IF NOT EXISTS partner_id uuid;
ALTER TABLE public.commission_payouts ADD COLUMN IF NOT EXISTS user_id uuid;
CREATE TABLE IF NOT EXISTS public.customer_payments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.customers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.daily_reconciliation (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.expense_categories (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.expenses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS user_id uuid;
CREATE TABLE IF NOT EXISTS public.ingredients (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.invoice_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.location_settings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
ALTER TABLE public.location_settings ADD COLUMN IF NOT EXISTS key text;
ALTER TABLE public.location_settings ADD COLUMN IF NOT EXISTS user_id uuid;
CREATE TABLE IF NOT EXISTS public.locations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.organizations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
ALTER TABLE public.organizations ADD COLUMN IF NOT EXISTS user_id uuid;
CREATE TABLE IF NOT EXISTS public.partner_applications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.partners (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
ALTER TABLE public.partners ADD COLUMN IF NOT EXISTS user_id uuid;
CREATE TABLE IF NOT EXISTS public.payment_methods (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.period_locks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
ALTER TABLE public.period_locks ADD COLUMN IF NOT EXISTS user_id uuid;
CREATE TABLE IF NOT EXISTS public.product_location_prices (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.product_stock (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
ALTER TABLE public.product_stock ADD COLUMN IF NOT EXISTS user_id uuid;
CREATE TABLE IF NOT EXISTS public.production_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.products (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.promotion_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
ALTER TABLE public.promotion_items ADD COLUMN IF NOT EXISTS promotion_id uuid;
CREATE TABLE IF NOT EXISTS public.promotions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.purchase_order_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
ALTER TABLE public.purchase_order_items ADD COLUMN IF NOT EXISTS po_id uuid;
CREATE TABLE IF NOT EXISTS public.purchase_orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.purchases (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.ra_notes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.recipes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.referrals (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
ALTER TABLE public.referrals ADD COLUMN IF NOT EXISTS partner_id uuid;
ALTER TABLE public.referrals ADD COLUMN IF NOT EXISTS user_id uuid;
CREATE TABLE IF NOT EXISTS public.report_subscriptions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.sales (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.shifts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.stock_adjustments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.stock_count_audit (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.stock_counts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.stock_movements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.stock_oversells (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.stock_receipt_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.stock_receipts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.stock_transfers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
ALTER TABLE public.stock_transfers ADD COLUMN IF NOT EXISTS from_location_id uuid;
ALTER TABLE public.stock_transfers ADD COLUMN IF NOT EXISTS to_location_id uuid;
CREATE TABLE IF NOT EXISTS public.suppliers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.wms_adjustments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.wms_catalog (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.wms_dispatch_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.wms_dispatches (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.wms_inventory (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.wms_locations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.wms_org_settings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.wms_po_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.wms_purchase_orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.wms_receipt_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.wms_receipts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.wms_stock_count_audit (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.wms_stock_count_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.wms_stock_counts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.wms_transfer_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.wms_transfers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.zra_config (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);
CREATE TABLE IF NOT EXISTS public.zra_invoices (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid,
  location_id uuid,
  recorded_by_user_id uuid
);

-- ---- policies (verbatim from the prod dump) -------------------------
CREATE POLICY "admin_overrides_read" ON public.admin_org_overrides FOR SELECT
  USING ((EXISTS ( SELECT 1
   FROM platform_admins pa
  WHERE (pa.user_id = auth.uid()))));
CREATE POLICY "app_settings_org_insert" ON public.app_settings FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "app_settings_org_delete" ON public.app_settings FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "app_settings_org_read" ON public.app_settings FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "app_settings_org_update" ON public.app_settings FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "audit_logs_org_read" ON public.audit_logs FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "balance_adjustments_loc_insert" ON public.balance_adjustments FOR INSERT
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "balance_adjustments_loc_delete" ON public.balance_adjustments FOR DELETE
  USING (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "balance_adjustments_loc_read" ON public.balance_adjustments FOR SELECT
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "balance_adjustments_loc_update" ON public.balance_adjustments FOR UPDATE
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))))
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "categories_org_insert" ON public.categories FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "categories_org_delete" ON public.categories FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "categories_org_read" ON public.categories FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "categories_org_update" ON public.categories FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "combo_items_insert" ON public.combo_items FOR INSERT
  WITH CHECK ((combo_id IN ( SELECT combos.id
   FROM combos
  WHERE (combos.org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))));
CREATE POLICY "combo_items_delete" ON public.combo_items FOR DELETE
  USING ((combo_id IN ( SELECT combos.id
   FROM combos
  WHERE (combos.org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))));
CREATE POLICY "combo_items_read" ON public.combo_items FOR SELECT
  USING ((combo_id IN ( SELECT combos.id
   FROM combos
  WHERE (combos.org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))));
CREATE POLICY "combos_insert" ON public.combos FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "combos_delete" ON public.combos FOR DELETE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "combos_read" ON public.combos FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "combos_update" ON public.combos FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "payouts_admin_all" ON public.commission_payouts FOR ALL
  USING (is_platform_admin())
  WITH CHECK (is_platform_admin());
CREATE POLICY "payouts_select_own" ON public.commission_payouts FOR SELECT
  USING (((partner_id IN ( SELECT partners.id
   FROM partners
  WHERE (partners.user_id = auth.uid()))) OR is_platform_admin()));
CREATE POLICY "customer_payments_loc_insert" ON public.customer_payments FOR INSERT
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "customer_payments_loc_delete" ON public.customer_payments FOR DELETE
  USING (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "customer_payments_loc_read" ON public.customer_payments FOR SELECT
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "customer_payments_loc_update" ON public.customer_payments FOR UPDATE
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))))
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "customers_loc_insert" ON public.customers FOR INSERT
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "customers_loc_delete" ON public.customers FOR DELETE
  USING (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "customers_loc_read" ON public.customers FOR SELECT
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "customers_loc_update" ON public.customers FOR UPDATE
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))))
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "daily_reconciliation_org_insert" ON public.daily_reconciliation FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "daily_reconciliation_org_delete" ON public.daily_reconciliation FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "daily_reconciliation_org_read" ON public.daily_reconciliation FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "daily_reconciliation_org_update" ON public.daily_reconciliation FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "expense_categories_org_insert" ON public.expense_categories FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "expense_categories_org_delete" ON public.expense_categories FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "expense_categories_org_read" ON public.expense_categories FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "expense_categories_org_update" ON public.expense_categories FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "expenses_loc_insert" ON public.expenses FOR INSERT
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids))) AND ((recorded_by_user_id IS NULL) OR (recorded_by_user_id = auth.uid()))));
CREATE POLICY "expenses_loc_delete" ON public.expenses FOR DELETE
  USING (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids))) AND ((EXISTS ( SELECT 1
   FROM org_members m
  WHERE ((m.org_id = expenses.org_id) AND (m.user_id = auth.uid()) AND (m.role = ANY (ARRAY['owner'::text, 'admin'::text]))))) OR (recorded_by_user_id = auth.uid()))));
CREATE POLICY "expenses_loc_read" ON public.expenses FOR SELECT
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids))) AND ((EXISTS ( SELECT 1
   FROM org_members m
  WHERE ((m.org_id = expenses.org_id) AND (m.user_id = auth.uid()) AND (m.role = ANY (ARRAY['owner'::text, 'admin'::text]))))) OR (recorded_by_user_id = auth.uid()))));
CREATE POLICY "expenses_loc_update" ON public.expenses FOR UPDATE
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids))) AND ((EXISTS ( SELECT 1
   FROM org_members m
  WHERE ((m.org_id = expenses.org_id) AND (m.user_id = auth.uid()) AND (m.role = ANY (ARRAY['owner'::text, 'admin'::text]))))) OR (recorded_by_user_id = auth.uid()))))
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "ingredients_org_insert" ON public.ingredients FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "ingredients_org_delete" ON public.ingredients FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "ingredients_org_read" ON public.ingredients FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "ingredients_org_update" ON public.ingredients FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "invoice_events_org_read" ON public.invoice_events FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "location_settings_insert" ON public.location_settings FOR INSERT
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids))));
CREATE POLICY "location_settings_delete" ON public.location_settings FOR DELETE
  USING (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids))));
CREATE POLICY "location_settings_read" ON public.location_settings FOR SELECT
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)) AND ((key <> ALL (ARRAY['admin_pin'::text, 'cashier_pin'::text])) OR (EXISTS ( SELECT 1
   FROM org_members om
  WHERE ((om.org_id = location_settings.org_id) AND (om.user_id = auth.uid()) AND (om.role = ANY (ARRAY['owner'::text, 'admin'::text]))))))));
CREATE POLICY "location_settings_update" ON public.location_settings FOR UPDATE
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids))))
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids))));
CREATE POLICY "locations_org_insert" ON public.locations FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "locations_org_delete" ON public.locations FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "locations_org_read" ON public.locations FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "locations_org_update" ON public.locations FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "member_insert_owner" ON public.org_members FOR INSERT
  WITH CHECK ((org_id IN ( SELECT org_members_1.org_id
   FROM org_members org_members_1
  WHERE ((org_members_1.user_id = auth.uid()) AND (org_members_1.role = 'owner'::text)))));
CREATE POLICY "member_delete_own_or_owner" ON public.org_members FOR DELETE
  USING (((user_id = auth.uid()) OR (org_id IN ( SELECT org_members_1.org_id
   FROM org_members org_members_1
  WHERE ((org_members_1.user_id = auth.uid()) AND (org_members_1.role = 'owner'::text))))));
CREATE POLICY "member_read_own_org" ON public.org_members FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "org_read_own" ON public.organizations FOR SELECT
  USING ((id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "org_update_owner" ON public.organizations FOR UPDATE
  USING ((id IN ( SELECT org_members.org_id
   FROM org_members
  WHERE ((org_members.user_id = auth.uid()) AND (org_members.role = 'owner'::text)))))
  WITH CHECK ((id IN ( SELECT org_members.org_id
   FROM org_members
  WHERE ((org_members.user_id = auth.uid()) AND (org_members.role = 'owner'::text)))));
CREATE POLICY "partner_applications_admin_all" ON public.partner_applications FOR ALL
  USING (is_platform_admin())
  WITH CHECK (is_platform_admin());
CREATE POLICY "partners_admin_all" ON public.partners FOR ALL
  USING (is_platform_admin())
  WITH CHECK (is_platform_admin());
CREATE POLICY "partners_select_own" ON public.partners FOR SELECT
  USING (((user_id = auth.uid()) OR is_platform_admin()));
CREATE POLICY "payment_methods_org_insert" ON public.payment_methods FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "payment_methods_org_delete" ON public.payment_methods FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "payment_methods_org_read" ON public.payment_methods FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "payment_methods_org_update" ON public.payment_methods FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "period_locks_write" ON public.period_locks FOR ALL
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND (EXISTS ( SELECT 1
   FROM org_members
  WHERE ((org_members.org_id = period_locks.org_id) AND (org_members.user_id = auth.uid()) AND (org_members.role = 'owner'::text))))));
CREATE POLICY "period_locks_read" ON public.period_locks FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "platform_admins_admin_all" ON public.platform_admins FOR ALL
  USING (is_platform_admin())
  WITH CHECK (is_platform_admin());
CREATE POLICY "plp_insert" ON public.product_location_prices FOR INSERT
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids))));
CREATE POLICY "plp_delete" ON public.product_location_prices FOR DELETE
  USING (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids))));
CREATE POLICY "plp_read" ON public.product_location_prices FOR SELECT
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids))));
CREATE POLICY "plp_update" ON public.product_location_prices FOR UPDATE
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids))))
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids))));
CREATE POLICY "product_stock_insert" ON public.product_stock FOR INSERT
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)) AND (EXISTS ( SELECT 1
   FROM org_members m
  WHERE ((m.org_id = product_stock.org_id) AND (m.user_id = auth.uid()) AND (m.role = ANY (ARRAY['owner'::text, 'admin'::text])))))));
CREATE POLICY "product_stock_delete" ON public.product_stock FOR DELETE
  USING (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)) AND (EXISTS ( SELECT 1
   FROM org_members m
  WHERE ((m.org_id = product_stock.org_id) AND (m.user_id = auth.uid()) AND (m.role = ANY (ARRAY['owner'::text, 'admin'::text])))))));
CREATE POLICY "product_stock_read" ON public.product_stock FOR SELECT
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids))));
CREATE POLICY "product_stock_update" ON public.product_stock FOR UPDATE
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)) AND (EXISTS ( SELECT 1
   FROM org_members m
  WHERE ((m.org_id = product_stock.org_id) AND (m.user_id = auth.uid()) AND (m.role = ANY (ARRAY['owner'::text, 'admin'::text])))))))
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)) AND (EXISTS ( SELECT 1
   FROM org_members m
  WHERE ((m.org_id = product_stock.org_id) AND (m.user_id = auth.uid()) AND (m.role = ANY (ARRAY['owner'::text, 'admin'::text])))))));
CREATE POLICY "production_log_org_insert" ON public.production_log FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "production_log_org_delete" ON public.production_log FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "production_log_org_read" ON public.production_log FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "production_log_org_update" ON public.production_log FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "products_org_insert" ON public.products FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "products_org_delete" ON public.products FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "products_org_read" ON public.products FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "products_org_update" ON public.products FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "promotion_items_insert" ON public.promotion_items FOR INSERT
  WITH CHECK ((promotion_id IN ( SELECT promotions.id
   FROM promotions
  WHERE (promotions.org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))));
CREATE POLICY "promotion_items_delete" ON public.promotion_items FOR DELETE
  USING ((promotion_id IN ( SELECT promotions.id
   FROM promotions
  WHERE (promotions.org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))));
CREATE POLICY "promotion_items_read" ON public.promotion_items FOR SELECT
  USING ((promotion_id IN ( SELECT promotions.id
   FROM promotions
  WHERE (promotions.org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))));
CREATE POLICY "promotions_insert" ON public.promotions FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "promotions_delete" ON public.promotions FOR DELETE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "promotions_read" ON public.promotions FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "promotions_update" ON public.promotions FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "purchase_order_items_insert" ON public.purchase_order_items FOR INSERT
  WITH CHECK ((po_id IN ( SELECT purchase_orders.id
   FROM purchase_orders
  WHERE (purchase_orders.org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))));
CREATE POLICY "purchase_order_items_delete" ON public.purchase_order_items FOR DELETE
  USING ((po_id IN ( SELECT purchase_orders.id
   FROM purchase_orders
  WHERE (purchase_orders.org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))));
CREATE POLICY "purchase_order_items_read" ON public.purchase_order_items FOR SELECT
  USING ((po_id IN ( SELECT purchase_orders.id
   FROM purchase_orders
  WHERE (purchase_orders.org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))));
CREATE POLICY "purchase_orders_insert" ON public.purchase_orders FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "purchase_orders_delete" ON public.purchase_orders FOR DELETE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "purchase_orders_read" ON public.purchase_orders FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "purchase_orders_update" ON public.purchase_orders FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "purchases_org_insert" ON public.purchases FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "purchases_org_delete" ON public.purchases FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "purchases_org_read" ON public.purchases FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "purchases_org_update" ON public.purchases FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "ra_notes_org_insert" ON public.ra_notes FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "ra_notes_org_delete" ON public.ra_notes FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "ra_notes_org_read" ON public.ra_notes FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "ra_notes_org_update" ON public.ra_notes FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "recipes_org_insert" ON public.recipes FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "recipes_org_delete" ON public.recipes FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "recipes_org_read" ON public.recipes FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "recipes_org_update" ON public.recipes FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "referrals_admin_all" ON public.referrals FOR ALL
  USING (is_platform_admin())
  WITH CHECK (is_platform_admin());
CREATE POLICY "referrals_select_own" ON public.referrals FOR SELECT
  USING (((partner_id IN ( SELECT partners.id
   FROM partners
  WHERE (partners.user_id = auth.uid()))) OR is_platform_admin()));
CREATE POLICY "report_subs_insert" ON public.report_subscriptions FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "report_subs_delete" ON public.report_subscriptions FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "report_subs_read" ON public.report_subscriptions FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "report_subs_update" ON public.report_subscriptions FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "sales_loc_insert" ON public.sales FOR INSERT
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "sales_loc_delete" ON public.sales FOR DELETE
  USING (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "sales_loc_read" ON public.sales FOR SELECT
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "sales_loc_update" ON public.sales FOR UPDATE
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))))
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "shifts_loc_insert" ON public.shifts FOR INSERT
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "shifts_loc_delete" ON public.shifts FOR DELETE
  USING (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "shifts_loc_read" ON public.shifts FOR SELECT
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "shifts_loc_update" ON public.shifts FOR UPDATE
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))))
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "stock_adjustments_loc_insert" ON public.stock_adjustments FOR INSERT
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "stock_adjustments_loc_delete" ON public.stock_adjustments FOR DELETE
  USING (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "stock_adjustments_loc_read" ON public.stock_adjustments FOR SELECT
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "stock_adjustments_loc_update" ON public.stock_adjustments FOR UPDATE
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))))
  WITH CHECK (((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)) AND ((location_id IS NULL) OR (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "stock_count_audit_org_insert" ON public.stock_count_audit FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "stock_count_audit_org_delete" ON public.stock_count_audit FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "stock_count_audit_org_read" ON public.stock_count_audit FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "stock_count_audit_org_update" ON public.stock_count_audit FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "stock_counts_write_location" ON public.stock_counts FOR ALL
  USING ((location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))
  WITH CHECK ((location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)));
CREATE POLICY "stock_counts_org_insert" ON public.stock_counts FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "stock_counts_org_delete" ON public.stock_counts FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "stock_counts_org_read" ON public.stock_counts FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "stock_counts_read_location" ON public.stock_counts FOR SELECT
  USING ((location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)));
CREATE POLICY "stock_counts_org_update" ON public.stock_counts FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "stock_movements_org_read" ON public.stock_movements FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "stock_oversells_read" ON public.stock_oversells FOR SELECT
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND (location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids))));
CREATE POLICY "stock_receipt_items_org_insert" ON public.stock_receipt_items FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "stock_receipt_items_org_delete" ON public.stock_receipt_items FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "stock_receipt_items_org_read" ON public.stock_receipt_items FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "stock_receipt_items_org_update" ON public.stock_receipt_items FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "stock_receipts_org_insert" ON public.stock_receipts FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "stock_receipts_org_delete" ON public.stock_receipts FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "stock_receipts_org_read" ON public.stock_receipts FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "stock_receipts_org_update" ON public.stock_receipts FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "stock_transfers_read" ON public.stock_transfers FOR SELECT
  USING (((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)) AND ((from_location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)) OR (to_location_id IN ( SELECT current_user_location_ids() AS current_user_location_ids)))));
CREATE POLICY "suppliers_org_insert" ON public.suppliers FOR INSERT
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "suppliers_org_delete" ON public.suppliers FOR DELETE
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "suppliers_org_read" ON public.suppliers FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "suppliers_org_update" ON public.suppliers FOR UPDATE
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "org_isolation" ON public.wms_adjustments FOR ALL
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "org_isolation" ON public.wms_catalog FOR ALL
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "org_isolation" ON public.wms_dispatch_items FOR ALL
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "org_isolation" ON public.wms_dispatches FOR ALL
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "org_isolation" ON public.wms_inventory FOR ALL
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "wms_locations_org_write" ON public.wms_locations FOR ALL
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "wms_locations_org_read" ON public.wms_locations FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "wms_org_settings_org_write" ON public.wms_org_settings FOR ALL
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "wms_org_settings_org_read" ON public.wms_org_settings FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "org_isolation" ON public.wms_po_items FOR ALL
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "org_isolation" ON public.wms_purchase_orders FOR ALL
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "org_isolation" ON public.wms_receipt_items FOR ALL
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "org_isolation" ON public.wms_receipts FOR ALL
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "org_isolation" ON public.wms_stock_count_audit FOR ALL
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "wms_scs_org_isolation" ON public.wms_stock_count_sessions FOR ALL
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "org_isolation" ON public.wms_stock_counts FOR ALL
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)))
  WITH CHECK ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "wms_transfer_items_org_read" ON public.wms_transfer_items FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "wms_transfers_org_read" ON public.wms_transfers FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "zra_config_write" ON public.zra_config FOR ALL
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "zra_config_read" ON public.zra_config FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));
CREATE POLICY "zra_invoices_write" ON public.zra_invoices FOR ALL
  USING ((org_id IN ( SELECT current_user_writable_org_ids() AS current_user_writable_org_ids)));
CREATE POLICY "zra_invoices_read" ON public.zra_invoices FOR SELECT
  USING ((org_id IN ( SELECT current_user_org_ids() AS current_user_org_ids)));

-- ---- enable RLS ---------------------------------------------------
ALTER TABLE public.admin_org_overrides ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.balance_adjustments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.combo_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.combos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.commission_payouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_reconciliation ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expense_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ingredients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.location_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.org_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.partner_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.partners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_methods ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.period_locks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.platform_admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_location_prices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_stock ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.production_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promotion_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promotions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ra_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.referrals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.report_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shifts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_adjustments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_count_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_counts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_oversells ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_receipt_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_transfers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wms_adjustments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wms_catalog ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wms_dispatch_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wms_dispatches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wms_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wms_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wms_org_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wms_po_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wms_purchase_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wms_receipt_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wms_receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wms_stock_count_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wms_stock_count_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wms_stock_counts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wms_transfer_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wms_transfers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zra_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zra_invoices ENABLE ROW LEVEL SECURITY;
