-- Migration 078: Security hardening — billing column protection + sales immutability
--
-- Fixes two critical findings from a security review:
-- 1. "org_update_owner" (migration 017) lets any owner UPDATE any column on
--    organizations via PostgREST, including subscription_plan,
--    subscription_status, trial_ends_at and every billing_* column — a user
--    with browser devtools could grant themselves a paid plan for free.
-- 2. "sales_org_update" / "sales_org_delete" (migration 017's per-table loop)
--    let any org member UPDATE or DELETE sales rows directly via PostgREST.
--    The only legitimate mutation paths are the SECURITY DEFINER RPCs
--    void_sale_lines (074) and record_sale_return (064), which bypass RLS
--    entirely and are unaffected by dropping these policies.
--
-- Idempotent: safe to re-run if partially applied.

BEGIN;

-- ============================================================
-- Part 1: Protect billing columns from client-side mutation
-- ============================================================

-- BEFORE UPDATE trigger silently restores billing columns to their prior
-- value whenever the caller is an authenticated user (PostgREST via the
-- authenticated role). Billing updates are written exclusively by the
-- admin/service-role client in the webhook handlers, which is not the
-- 'authenticated' role and so is unaffected.

CREATE OR REPLACE FUNCTION protect_billing_columns()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF current_setting('request.jwt.claim.role', true) = 'authenticated' THEN
    NEW.subscription_plan       := OLD.subscription_plan;
    NEW.subscription_status     := OLD.subscription_status;
    NEW.trial_ends_at           := OLD.trial_ends_at;
    NEW.billing_provider        := OLD.billing_provider;
    NEW.billing_customer_id     := OLD.billing_customer_id;
    NEW.billing_subscription_id := OLD.billing_subscription_id;
    NEW.billing_currency        := OLD.billing_currency;
    NEW.last_charge_minor       := OLD.last_charge_minor;
    NEW.last_charge_at          := OLD.last_charge_at;
    NEW.current_period_end      := OLD.current_period_end;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_protect_billing ON organizations;
CREATE TRIGGER trg_protect_billing
  BEFORE UPDATE ON organizations
  FOR EACH ROW
  EXECUTE FUNCTION protect_billing_columns();

-- ============================================================
-- Part 2: Sales immutability — block client UPDATE/DELETE
-- ============================================================

-- Drop the permissive UPDATE and DELETE policies on sales (generated by
-- migration 017's per-table loop as sales_org_update / sales_org_delete).
-- SELECT and INSERT remain untouched. Without an UPDATE/DELETE policy,
-- PostgREST cannot mutate sales rows for the 'authenticated' role — it
-- affects zero rows rather than erroring. void_sale_lines and
-- record_sale_return are SECURITY DEFINER and bypass RLS entirely, so
-- voids and returns continue to work exactly as before.

DROP POLICY IF EXISTS "sales_org_update" ON sales;
DROP POLICY IF EXISTS "sales_org_delete" ON sales;

COMMIT;
